docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only
  merge:
    - bash .ci/check_maintainership.sh

decrypt:
  rultor_github_secrets.sh: "repo/.ci/rultor_github_secrets.sh.asc"
